# Generated by Django 6.1 on 2026-09-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='no_of_articles',
        ),
    ]
