# Generated by Django 6.1 on 2026-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_authors_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='address',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authors',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Author Name'),
        ),
    ]

